export const SECTION_TYPES = [
  { value: "hero", label: "Hero" },
  { value: "clients", label: "Clients" },
  { value: "about", label: "About Us" },
  { value: "track", label: "Track" },
  { value: "technology_platform", label: "Technology Platform" },
  { value: "trusted_industries", label: "Trusted across industries" },
  { value: "footprints", label: "Footprints Software" },
  { value: "services", label: "Services" },
  { value: "stats", label: "Stats" },
  { value: "team", label: "Team" },
  { value: "gallery", label: "Gallery" },
  { value: "faq", label: "FAQ" },
  { value: "testimonials", label: "Testimonials" },
  { value: "more_clients", label: "More clients" },
  { value: "about_page_hero", label: "About Hero" },
  { value: "who_we_are_about", label: "Who we are - About" },
  { value: "our_journey_about", label: "Our Journey - About" },
  { value: "what_we_deliver_about", label: "What We Deliver - About" },
  { value: "reach_trust_about", label: "Reach & Trust - About" },
  { value: "page_hero", label: "Reusable Page Hero" },
  { value: "page_clients", label: "Reusable Client Logos" },
  { value: "asset_management_solution", label: "Reusable Asset Management Software Solution" },
  { value: "page_faq", label: "Reusable FAQ" },
  { value: "page_cta", label: "Reusable CTA" },
  { value: "cta_reusable", label: "CTA - Reusable" },
  { value: "resource_page_hero", label: "Resource Page Hero" },
  { value: "hero_section_service_page", label: "Hero Section - Service Page" },
  { value: "services_intro_section_service_page", label: "Services Intro - Service Page" },
  { value: "services_catalogue_section_service_page", label: "Services Catalogue - Service Page" },
  { value: "services_execution_section_service_page", label: "Services Execution - Service Page" },
  { value: "hero_section_tools", label: "Hero Section - Tools" },
  { value: "tools_intro_section_tools", label: "Tools Intro - Tools" },
  { value: "tools_flagship_section_tools", label: "Tools Flagship - Tools" },
  { value: "tools_cta_section_tools", label: "Tools CTA - Tools" },
  { value: "hero_section_software", label: "Hero Section - Software" },
  { value: "software_intro_section_software", label: "Software Intro - Software" },
  { value: "software_modules_section_software", label: "Software Modules - Software" },
  { value: "software_cta_section_software", label: "Software CTA - Software" },
  { value: "cta", label: "Call to Action" },
  { value: "timeline", label: "Timeline" },
  { value: "contact_form", label: "Contact Form" },
  { value: "pricing", label: "Pricing" },
  { value: "article_body", label: "Article Body" },
  { value: "rich_text", label: "Rich Text" },
  { value: "video", label: "Video" },
  { value: "partners", label: "Partners" },
] as const;

export type SectionType = (typeof SECTION_TYPES)[number]["value"];
