export const SECTION_TYPES = [
  { value: "hero", label: "Hero" },
  { value: "clients", label: "Clients" },
  { value: "about", label: "About Us" },
  { value: "track", label: "Track" },
  { value: "technology_platform", label: "Technology Platform" },
  { value: "trusted_industries", label: "Trusted across industries" },
  { value: "footprints", label: "Footprints Software" },
  { value: "services", label: "Services" },
  { value: "stats", label: "Stats" },
  { value: "team", label: "Team" },
  { value: "gallery", label: "Gallery" },
  { value: "faq", label: "FAQ" },
  { value: "testimonials", label: "Testimonials" },
  { value: "more_clients", label: "More clients" },
  { value: "about_page_hero", label: "About Hero" },
  { value: "who_we_are_about", label: "Who we are - About" },
  { value: "our_journey_about", label: "Our Journey - About" },
  { value: "what_we_deliver_about", label: "What We Deliver - About" },
  { value: "reach_trust_about", label: "Reach & Trust - About" },
  { value: "resource_page_hero", label: "Resource Page Hero" },
  { value: "cta", label: "Call to Action" },
  { value: "timeline", label: "Timeline" },
  { value: "contact_form", label: "Contact Form" },
  { value: "pricing", label: "Pricing" },
  { value: "rich_text", label: "Rich Text" },
  { value: "video", label: "Video" },
  { value: "partners", label: "Partners" },
] as const;

export type SectionType = (typeof SECTION_TYPES)[number]["value"];
